# Generated by Django 3.0.7 on 2021-02-24 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySiscoriFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries_filters', models.CharField(max_length=100, verbose_name='countries_filter')),
            ],
        ),
        migrations.CreateModel(
            name='NcmSiscoriFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm_filters', models.CharField(max_length=100, verbose_name='ncm_filters')),
            ],
        ),
        migrations.CreateModel(
            name='SiscoriFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='siscori_files', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
            ],
        ),
        migrations.CreateModel(
            name='SiscoriHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.CharField(max_length=100, verbose_name='files')),
                ('n_filters', models.CharField(max_length=500, verbose_name='n_filters')),
                ('c_filters', models.CharField(max_length=500, verbose_name='c_filters')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiscoriUnknownData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=4000, verbose_name='description')),
                ('ncm', models.CharField(max_length=50, verbose_name='ncm')),
                ('harbor', models.CharField(max_length=50, verbose_name='harbor')),
                ('purchase_country', models.CharField(max_length=50, verbose_name='purchase_country')),
                ('origin_country', models.CharField(max_length=50, verbose_name='origin_country')),
                ('month', models.IntegerField(verbose_name='month')),
                ('year', models.IntegerField(verbose_name='year')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('value', models.FloatField(max_length=50, verbose_name='value')),
            ],
        ),
    ]
